// src/lib/sampleData.ts
import type { Post, Product } from "@/types/community";

export const SAMPLE_POSTS: Record<string, Post[]> = {
  free: [
    {
      postId: 1, memberId: 1, boardId: 1,
      title: "중간고사 끝나고 다 같이 MT 갈 사람?",
      content: "중간고사도 끝났는데 다 같이 바람 쐬러 가요! 1박 2일로 생각하고 있어요.",
      category: "모임",
      viewCount: 142, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "12분 전",
      authorName: "김서연", authorNickname: "서연스터디",
      likeCount: 24, commentCount: 18, isHot: true,
    },
    {
      postId: 2, memberId: 2, boardId: 1,
      title: "도서관 3층 콘센트 자리 명당 공유합니다",
      content: "3층 창가쪽이 콘센트 제일 많아요.",
      category: "정보",
      viewCount: 320, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "1시간 전",
      authorName: "이준호", authorNickname: "준호",
      likeCount: 56, commentCount: 12, isHot: true,
    },
    {
      postId: 3, memberId: 3, boardId: 1,
      title: "이번 학기 꿀교양 추천 좀 해주세요",
      content: "수강신청 앞두고 교양 추천 부탁드려요.",
      category: "질문",
      viewCount: 210, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "3시간 전",
      authorName: "박지민", authorNickname: "지민",
      likeCount: 31, commentCount: 42,
    },
    {
      postId: 4, memberId: 4, boardId: 1,
      title: "학식 새 메뉴 먹어본 사람 후기 좀",
      content: "오늘 학식에 새 메뉴 나왔던데 어때요?",
      category: "잡담",
      viewCount: 88, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "5시간 전",
      authorName: "최유나", authorNickname: "유나",
      likeCount: 9, commentCount: 7,
    },
    {
      postId: 5, memberId: 5, boardId: 1,
      title: "동아리 박람회 부스 위치 정리해봤어요",
      content: "동아리 박람회 부스 위치 정리해봤어요.",
      category: "정보",
      viewCount: 540, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "어제",
      authorName: "정태현", authorNickname: "태현",
      likeCount: 88, commentCount: 5,
    },
  ],
  secret: [
    {
      postId: 11, memberId: 1, boardId: 2,
      title: "조별과제 무임승차 어떻게 대처하세요...",
      content: "조별과제에서 무임승차하는 팀원이 있어요. 어떻게 대처하셨나요?",
      category: "고민",
      viewCount: 180, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "8분 전",
      authorName: "익명", authorNickname: "익명",
      likeCount: 42, commentCount: 27, isHot: true, isAnonymous: true,
    },
    {
      postId: 12, memberId: 2, boardId: 2,
      title: "자취 vs 기숙사 진지하게 고민됩니다",
      content: "자취랑 기숙사 중에 어떤 게 나을까요?",
      category: "고민",
      viewCount: 150, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "2시간 전",
      authorName: "익명", authorNickname: "익명",
      likeCount: 18, commentCount: 33, isAnonymous: true,
    },
    {
      postId: 13, memberId: 3, boardId: 2,
      title: "교수님께 메일 보낼 때 너무 떨려요",
      content: "교수님께 처음 메일 보내는데 너무 떨려요.",
      category: "잡담",
      viewCount: 96, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "4시간 전",
      authorName: "익명", authorNickname: "익명",
      likeCount: 25, commentCount: 14, isAnonymous: true,
    },
    {
      postId: 14, memberId: 4, boardId: 2,
      title: "과 동기한테 고백할까요 말까요",
      content: "과 동기인데 요즘 계속 생각나요. 고백해도 될까요?",
      category: "고민",
      viewCount: 388, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "어제",
      authorName: "익명", authorNickname: "익명",
      likeCount: 61, commentCount: 44, isAnonymous: true, isHot: true,
    },
    {
      postId: 15, memberId: 5, boardId: 2,
      title: "장학금 면담 다녀온 후기",
      content: "장학금 면담 다녀왔는데 생각보다 편했어요.",
      category: "정보",
      viewCount: 201, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "어제",
      authorName: "익명", authorNickname: "익명",
      likeCount: 33, commentCount: 21, isAnonymous: true,
    },
    {
      postId: 16, memberId: 1, boardId: 2,
      title: "특정 학우 비방하는 내용입니다",
      content: "비방 내용",
      category: "잡담",
      viewCount: 0, isBlind: 1, reportCount: 7, isDeleted: 0,
      createdAt: "3시간 전",
      authorName: "익명", authorNickname: "익명",
      likeCount: 0, commentCount: 4, isAnonymous: true,
    },
  ],
  notice: [
    {
      postId: 21, memberId: 1, boardId: 3,
      title: "2학기 수강신청 일정 안내",
      content: "2학기 수강신청 일정을 안내드립니다.",
      category: "학사",
      viewCount: 0, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "오늘",
      authorName: "교무처", authorNickname: "교무처",
      likeCount: 0, commentCount: 0, tag: "중요",
    },
    {
      postId: 22, memberId: 1, boardId: 3,
      title: "중앙도서관 열람실 운영시간 변경 안내",
      content: "도서관 열람실 운영시간이 변경됩니다.",
      category: "시설",
      viewCount: 0, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "어제",
      authorName: "학술정보원", authorNickname: "학술정보원",
      likeCount: 0, commentCount: 0, tag: "공지",
    },
    {
      postId: 23, memberId: 1, boardId: 3,
      title: "교내 분실물 보관 및 처리 안내",
      content: "교내 분실물 보관 및 처리 안내입니다.",
      category: "생활",
      viewCount: 0, isBlind: 0, reportCount: 0, isDeleted: 0,
      createdAt: "3일 전",
      authorName: "학생지원팀", authorNickname: "학생지원팀",
      likeCount: 0, commentCount: 0, tag: "공지",
    },
  ],
};

export const SAMPLE_PRODUCTS: Product[] = [
  {
    productId: 1, memberId: 1,
    productName: "자료구조 전공서적 (거의 새것)",
    price: 12000, category: "교재",
    place: "중앙도서관 앞",
    description: "한 학기 사용했고 필기는 연필로만 해서 지우면 깨끗해요.",
    viewCount: 86, isDeleted: 0,
    createdAt: "3분 전", productStatus: "SALE",
    sellerName: "김서연", sellerNickname: "서연스터디",
    likeCount: 4, chatCount: 2,
  },
  {
    productId: 2, memberId: 2,
    productName: "공학용 계산기 fx-991",
    price: 8000, category: "전자기기",
    place: "공대 1호관",
    description: "복학하면서 안 쓰게 됐어요. 작동 잘 되고 흠집 거의 없습니다.",
    viewCount: 142, isDeleted: 0,
    createdAt: "20분 전", productStatus: "SALE",
    sellerName: "이준호", sellerNickname: "준호",
    likeCount: 12, chatCount: 3,
  },
  {
    productId: 3, memberId: 3,
    productName: "LED 스탠드 (화이트)",
    price: 15000, category: "생활용품",
    place: "기숙사 A동",
    description: "밝기 3단계 조절되고 USB 충전식이에요.",
    viewCount: 64, isDeleted: 0,
    createdAt: "어제", productStatus: "DONE",
    sellerName: "박지민", sellerNickname: "지민",
    likeCount: 7, chatCount: 1,
  },
  {
    productId: 4, memberId: 4,
    productName: "맥북 거치대 알루미늄",
    price: 20000, category: "전자기기",
    place: "학생회관",
    description: "높이 조절되는 알루미늄 거치대입니다.",
    viewCount: 230, isDeleted: 0,
    createdAt: "어제", productStatus: "SALE",
    sellerName: "최유나", sellerNickname: "유나",
    likeCount: 18, chatCount: 5,
  },
  {
    productId: 5, memberId: 5,
    productName: "아이패드 펜슬 2세대",
    price: 55000, category: "전자기기",
    place: "중앙도서관",
    description: "정품이고 페어링 잘 됩니다. 필기감 좋아요.",
    viewCount: 410, isDeleted: 0,
    createdAt: "3일 전", productStatus: "RESERVE",
    sellerName: "오세훈", sellerNickname: "세훈",
    likeCount: 22, chatCount: 6,
  },
];

export const SAMPLE_POPULAR = [
  { title: "시험기간 집중력 2배 높이는 공부 루틴", board: "자유", viewCount: 3120 },
  { title: "조별과제 무임승차 어떻게 대처하세요", board: "익명", viewCount: 2870 },
  { title: "도서관 3층 콘센트 자리 명당 공유합니다", board: "자유", viewCount: 2440 },
  { title: "2학기 수강신청 일정 안내", board: "공지", viewCount: 2210 },
  { title: "자취방 구할 때 꼭 체크할 7가지", board: "자유", viewCount: 1980 },
  { title: "장학금 면담 다녀온 후기 (현실적인 팁)", board: "익명", viewCount: 1760 },
  { title: "이번 학기 꿀교양 추천 좀 해주세요", board: "자유", viewCount: 1540 },
];