// src/lib/sampleData.ts
import type { Post, Product } from '@/types/community';

export const SAMPLE_POSTS: Record<string, Post[]> = {
  free: [
    {
      postId: 1,
      title: '중간고사 끝나고 다 같이 MT 갈 사람?',
      author: '김서연',
      category: '모임',
      createdAt: '12분 전',
      likeCount: 24,
      commentCount: 18,
      viewCount: 142,
      isHot: true,
    },
    {
      postId: 2,
      title: '도서관 3층 콘센트 자리 명당 공유합니다',
      author: '이준호',
      category: '정보',
      createdAt: '1시간 전',
      likeCount: 56,
      commentCount: 12,
      viewCount: 320,
      isHot: true,
    },
    {
      postId: 3,
      title: '이번 학기 꿀교양 추천 좀 해주세요',
      author: '박지민',
      category: '질문',
      createdAt: '3시간 전',
      likeCount: 31,
      commentCount: 42,
      viewCount: 210,
    },
    {
      postId: 4,
      title: '학식 새 메뉴 먹어본 사람 후기 좀',
      author: '최유나',
      category: '잡담',
      createdAt: '5시간 전',
      likeCount: 9,
      commentCount: 7,
      viewCount: 88,
    },
    {
      postId: 5,
      title: '동아리 박람회 부스 위치 정리해봤어요',
      author: '정태현',
      category: '정보',
      createdAt: '어제',
      likeCount: 88,
      commentCount: 5,
      viewCount: 540,
    },
  ],
  secret: [
    {
      postId: 11,
      title: '조별과제 무임승차 어떻게 대처하세요...',
      author: '익명',
      category: '고민',
      createdAt: '8분 전',
      likeCount: 42,
      commentCount: 27,
      viewCount: 180,
      isHot: true,
      isAnonymous: true,
    },
    {
      postId: 12,
      title: '자취 vs 기숙사 진지하게 고민됩니다',
      author: '익명',
      category: '고민',
      createdAt: '2시간 전',
      likeCount: 18,
      commentCount: 33,
      viewCount: 150,
      isAnonymous: true,
    },
    {
      postId: 13,
      title: '교수님께 메일 보낼 때 너무 떨려요',
      author: '익명',
      category: '잡담',
      createdAt: '4시간 전',
      likeCount: 25,
      commentCount: 14,
      viewCount: 96,
      isAnonymous: true,
    },
    {
      postId: 14,
      title: '장학금 면담 다녀온 후기',
      author: '익명',
      category: '정보',
      createdAt: '어제',
      likeCount: 33,
      commentCount: 21,
      viewCount: 201,
      isAnonymous: true,
    },
    {
      postId: 15,
      title: '과 동기한테 고백할까요 말까요',
      author: '익명',
      category: '고민',
      createdAt: '어제',
      likeCount: 61,
      commentCount: 44,
      viewCount: 388,
      isAnonymous: true,
      isHot: true,
    },
    { 
      postId: 16,
      title: "특정 학우 비방하는 내용입니다", 
      author: "익명", 
      category: "잡담", 
      createdAt: "3시간 전", 
      likeCount: 0, 
      commentCount: 4, 
      viewCount: 0, 
      isAnonymous: true, 
      isBlind: true, 
      reportCount: 7 }
  ],
  notice: [
    {
      postId: 21,
      title: '2학기 수강신청 일정 안내',
      author: '교무처',
      category: '학사',
      createdAt: '오늘',
      likeCount: 0,
      commentCount: 0,
      viewCount: 0,
      tag: '중요',
    },
    {
      postId: 22,
      title: '중앙도서관 열람실 운영시간 변경 안내',
      author: '학술정보원',
      category: '시설',
      createdAt: '어제',
      likeCount: 0,
      commentCount: 0,
      viewCount: 0,
      tag: '공지',
    },
    {
      postId: 23,
      title: '교내 분실물 보관 및 처리 안내',
      author: '학생지원팀',
      category: '생활',
      createdAt: '3일 전',
      likeCount: 0,
      commentCount: 0,
      viewCount: 0,
      tag: '공지',
    },
  ],
};

export const SAMPLE_PRODUCTS: Product[] = [
  {
    productId: 1,
    productName: '자료구조 전공서적 (거의 새것)',
    price: 12000,
    category: '교재',
    sellerName: '김서연',
    place: '중앙도서관 앞',
    createdAt: '3분 전',
    likeCount: 4,
    chatCount: 2,
    viewCount: 86,
    productStatus: '판매중',
  },
  {
    productId: 2,
    productName: '공학용 계산기 fx-991',
    price: 8000,
    category: '전자기기',
    sellerName: '이준호',
    place: '공대 1호관',
    createdAt: '20분 전',
    likeCount: 12,
    chatCount: 3,
    viewCount: 142,
    productStatus: '판매중',
  },
  {
    productId: 3,
    productName: 'LED 스탠드 (화이트)',
    price: 15000,
    category: '생활용품',
    sellerName: '박지민',
    place: '기숙사 A동',
    createdAt: '어제',
    likeCount: 7,
    chatCount: 1,
    viewCount: 64,
    productStatus: '거래완료',
  },
  {
    productId: 4,
    productName: '맥북 거치대 알루미늄',
    price: 20000,
    category: '전자기기',
    sellerName: '최유나',
    place: '학생회관',
    createdAt: '어제',
    likeCount: 18,
    chatCount: 5,
    viewCount: 230,
    productStatus: '판매중',
  },
  {
    productId: 5,
    productName: '아이패드 펜슬 2세대',
    price: 55000,
    category: '전자기기',
    sellerName: '오세훈',
    place: '중앙도서관',
    createdAt: '3일 전',
    likeCount: 22,
    chatCount: 6,
    viewCount: 410,
    productStatus: '판매중',
  },
];

export const SAMPLE_POPULAR = [
  {
    title: '시험기간 집중력 2배 높이는 공부 루틴',
    board: '자유',
    viewCount: 3120,
  },
  {
    title: '조별과제 무임승차 어떻게 대처하세요',
    board: '익명',
    viewCount: 2870,
  },
  {
    title: '도서관 3층 콘센트 자리 명당 공유합니다',
    board: '자유',
    viewCount: 2440,
  },
  { title: '2학기 수강신청 일정 안내', board: '공지', viewCount: 2210 },
  { title: '자취방 구할 때 꼭 체크할 7가지', board: '자유', viewCount: 1980 },
  {
    title: '장학금 면담 다녀온 후기 (현실적인 팁)',
    board: '익명',
    viewCount: 1760,
  },
  {
    title: '이번 학기 꿀교양 추천 좀 해주세요',
    board: '자유',
    viewCount: 1540,
  },
];
